web_app/website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify, session, send_file
from flask_login import login_required, current_user
from .models import Note
from PIL import Image
from . import db
import io
import os
import sys
import shutil
import time
import csv

sys.path.insert(1, '/Users/jonathanapps/UCT/2023 (4TH YEAR)/Thesis_Work/code')
from code_main import mainProcessing

views  = Blueprint('views', __name__)
mainProcessor = None
process_time = 0

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    global process_time
    global mainProcessor
    process_time = 0
    if request.method == 'POST':
        try:
            print("Posting to home")
            # Check if an image was uploaded in the form
            if 'image' in request.files:
                
                print("Image is here!")
                uploaded_image = request.files['image']
                
                if uploaded_image:
                    start_time = time.time()
                    # Process the uploaded image (e.g., resize)
                    image = Image.open(io.BytesIO(uploaded_image.read()))
                    mainProcessor = mainProcessing(image)
                    new_image, new_labels = mainProcessor.insert_to_pipeline() # Feed the image to the pipeline to render image to be displayed next
                    
                    print("new_labels = ", new_labels)
                    process_time = time.time() - start_time
                    return redirect(url_for("views.valuation", new_labels=",".join(new_labels)))
            else:
                print("no image found")

        except Exception as e:
            flash(f'Error processing the image: {str(e)}', 'danger')
            
    return render_template("home.html", user=current_user)


@views.route('/valuation', methods=['GET', 'POST'])
@login_required
def valuation():
    global mainProcessor
    global process_time
    if mainProcessor is None:
        return redirect(url_for("views.home"))
    start_time = time.time()
    new_labels = request.args.get('new_labels')  # Retrieve new_labels as a comma-separated string
    if new_labels: new_labels = new_labels.split(',')  # Split the string to get the list of labels
    # Define a dictionary to map label prefixes to symbols
    symbol_mapping = {'DC':'V', 'AC':'V', 'L':'mH', 'R':'Ω', 'D':'None', 'C':'µF'}

    # Create indexed labels with symbols
    indexed_labels = []
    for index, label in enumerate(new_labels):
        # Extract the prefix (first two characters) of the label
        prefix = label[:2]
        if prefix in ['DC', 'AC']:
            symbol = symbol_mapping.get(prefix, None)
        else:
            symbol = symbol_mapping.get(prefix[0], None)  # Get the first character as symbol

        indexed_labels.append((index, label, symbol))
    session['indexed_labels'] = indexed_labels
    print("indexed labels = ", indexed_labels)
    process_time += (time.time() - start_time)
    return render_template("valuation.html", user=current_user, indexed_labels=indexed_labels)


@views.route('/results', methods=['GET', 'POST'])
@login_required
def results():
    global process_time
    global mainProcessor  # Access the global variable
    if mainProcessor is None:
        # Handle the case where mainProcessor is not yet initialized
        return redirect(url_for("views.home"))
    indexed_labels = session.get('indexed_labels', [])
    start_time = time.time()
    component_values = []
    for index, label, symbol in indexed_labels:
        input_name = f'label_{index}'
        component_values.append(request.form.get(input_name))
        
    print('Generating Netlist!')
    netlist_file = mainProcessor.process_image(component_values, indexed_labels) # Process the image
    print('Data processed successfully!')
    
    img_source_dir = '../web_app/'
    img_dest_dir = './website/static/images/'
    
    # Create the destination directory if it doesn't exist
    os.makedirs(img_dest_dir, exist_ok=True)
    
    # Iterate through files in the source directory
    for filename in os.listdir(img_source_dir):
        print("filename = ", filename)
        if filename.endswith('.png'):
            source_file = os.path.join(img_source_dir, filename)
            destination_file = os.path.join(img_dest_dir, filename)
            shutil.copy(source_file, destination_file)
    process_time += (time.time() - start_time) 
    
    # Specify the CSV file path
    csv_file = 'process_times.csv'
    # Open the CSV file in append mode and write the process_time value
    with open(csv_file, 'a', newline='') as csvfile:
        csv_writer = csv.writer(csvfile)
        csv_writer.writerow([process_time])
    print(f'Process time {process_time} saved to {csv_file}')
        
    return render_template("results.html", user=current_user, netlist_file = netlist_file)


@views.route('/download_file', methods=['GET', 'POST'])
@login_required
def download_file():
    # Define the path to the file in your local directory
    file_path = '../netlist.cir'  # Change this to the actual file path
    
    # Use Flask's send_file function to send the file for download
    return send_file(file_path, as_attachment=True)

web_app/website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset = 'utf-8' />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous"
        />
        <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous"
        />
        <title>{% block title %}Home{% endblock %}</title>
    
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                {% if user.is_authenticated %}
                    <div class="navbar-nav">
                        <a href="/">
                            <img src="../static/images/logo.png" alt="could not show image" class="img-fluid" width="40" height="20">
                        </a>
                    </div>
                    <div class="navbar-nav ml-auto">
                        <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                    </div>
                {% else %}
                    <div class="navbar-nav">
                        <a href="/login">
                            <img src="../static/images/logo.png" alt="could not show image" class="img-fluid" width="40" height="20">
                        </a>
                    </div>
                {% endif %}
                </div>
            </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=true)%}
            {% if messages %}
                {% for category, message in messages%}
                    {% if category == 'error' %}
                        <div class="alert alert-danger alter-dismissable fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% else %}
                        <div class="alert alert-success alter-dismissable fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endwith %}
        
        <div class="container">
            {% block content%}
            {% endblock %}
        </div>
        <script
            src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"
        ></script>
        <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
        ></script>
        <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
        ></script>
    </body>
</html>

web_app/website/templates/button.html
<div class="centerer">
    <div class="wrap">
      <a class="btn-0" href="#">Swipe</a>
    </div>
</div>
<style>
    @import url(https://fonts.googleapis.com/css?family=Open+Sans:400|Raleway:300);

    $btn-width: 250px !default;
    $btn-height: 80px !default;
    $btn-full: $btn-height+$btn-width !default;
    $btn-half: $btn-full/2 !default;
    $bg-color: #eeeeee !default;
    
    html {
      padding-top: 50px;
      font-family: 'Open Sans', Helvetica, arial, sans-serif;
      text-align: center;
      background-color: $bg-color;
    
      *,
      *:before,
      *:after {
        box-sizing: border-box;
        transition: 0.5s ease-in-out;
      }
    
      i,em,
      b,strong,
      span {
        transition: none;
      }
    }
    
    *:before,
    *:after {
      z-index: -1;
    }
    
    h1,
    h4 {
      font-family: 'Raleway', 'Open Sans', sans-serif;
      margin: 0;
      line-height: 1;
    }
    
    a {
      text-decoration: none;
      line-height: $btn-height;
      color: black;
    }
    
    .centerer {
      width: 100%;
      max-width: 600px;
      margin: 0 auto;
      padding: 0 1rem
    }
    
    @media (min-width: 600px) {
      .wrap {
        width: 50%;
        float: left;
      }
    }
    
    [class^="btn-"] {
      position: relative;
      display: block;
      overflow: hidden;
      @include size(100%, $btn-height);
      max-width: $btn-width;
      margin: 1rem auto;
      text-transform: uppercase;
      border: 1px solid currentColor;
    }
    
    .btn-0 {
      $btn-color: random-color($max:200);
      $btn-color-dark: shade($btn-color, 40%);
      color: tint($btn-color);
    
      &:before {
        content: '';
        @include absolute(0,0,0,0);
        background-color: $btn-color-dark;
        transform: translateX(-100%);
      }
    
      &:hover {
        color: tint($btn-color, 75%);
    
        &:before {
          transform: translateX(0);
        }
      }
    }
    
    .btn-1 {
      $btn-color: random-color($max:200);
      $btn-color-dark: shade($btn-color, 40%);
      color: tint($btn-color);
      
      &:before {
        content: '';
        @include absolute(0,-50px,0,0);
        border-right: 50px solid transparent;
        border-bottom: $btn-height solid $btn-color-dark;
        transform: translateX(-100%);
      }
    
      &:hover {
        color: tint($btn-color, 75%);
    
        &:before {
          transform: translateX(0);
        }
      }
    }
    
    .btn-1-2 {
      $btn-color: random-color($max:200);
      $btn-color-dark: shade($btn-color, 40%);
      color: tint($btn-color);
      
      &:before,
      &:after {
        content: '';
        @include absolute(0,0,0,0);
        border-bottom: $btn-height solid $btn-color-dark;
      }
      
      &:before {
        right: -50px;
        border-right: 50px solid transparent;
        transform: translateX(-100%);
      }
      
      &:after {
        left: -50px;
        border-left: 50px solid transparent;
        transform: translateX(100%);
      }
    
      &:hover {
        color: tint($btn-color, 75%);
    
        &:before { transform: translateX(-40%); }
        &:after { transform: translateX(40%); }
      }
    }

</style>

web_app/website/templates/login.html
{% extends "base.html" %}
{% block title %}Log In{% endblock%}
{% block content%}
<div class="container" style="margin-bottom: -30px; border-radius: 0px"> <!-- Remove margin-bottom -->
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="d-flex justify-content-center"> <!-- Center the card -->
                <div class="card mt-5" style="max-width: 350px; border-radius: 0px">

                    <div class="card-body" style="margin-bottom: 0px;">
                        <img src="../static/images/thesis_logo.png" alt="could not show image" class="img-fluid" style="margin-top: 20px;">
                        <br></br>

                        <form method="POST">
                            <div class="form-group" style="margin-left: 20px; margin-right: 20px; margin-bottom: 5px;">
                                <label for="username"></label>
                                <input style="font-size: 14px;"  type="text" class="form-control" id="username" name="username" placeholder="Username or email address">
                            </div>

                            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
                            <div class="form-group" style="margin-left: 20px; margin-right: 20px; margin-bottom: 5px;">
                                <label for="password"></label>
                                <div class="input-group"> <!-- Wrap the input field and the eye icon in an input-group -->
                                    <input style="font-size: 14px;" type="password" class="form-control" id="password" name="password" placeholder="Password">
                                    <div class="input-group-append"> <!-- Add the eye icon as an input-group-append -->
                                        <span class="input-group-text" onclick="togglePasswordVisibility()" style="cursor: pointer;"> <!-- Use cursor: pointer for the hand cursor on hover -->
                                            <i class="far fa-eye-slash"></i> <!-- The eye icon from Font Awesome (outline version) -->
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <br>
                            <div class="row justify-content-center" style="margin-left: 5px; margin-right: 5px;">
                                <div class="col-12 text-center"> <!-- Adjust column width to control button position -->
                                    <div class="d-flex justify-content-center"> <!-- Center the button -->
                                        <button style="font-size: 13px;" type="submit" class="btn btn-primary btn-fixed-width">Log In</button>
                                    </div>
                                </div>
                            </div>                       
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container"> <!-- Remove margin-bottom and extra row/column -->
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="d-flex justify-content-center"> <!-- Center the card -->
                <div class="card mt-5" style="width: 350px; height: 70px; border-radius: 0px">
                    <div class="card-body">
                        <form method="POST">
                            <p style="text-align: center; font-size: 15px; font-family: Arial, sans-serif;"> <!-- Center the text and apply custom font size and font-family -->
                                <a>Don't have an account? </a>
                                <a href="/sign-up">Sign Up</a>
                            </p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Add Bootstrap JS (optional if you require JS features) -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script>
    function togglePasswordVisibility() {
        const passwordInput = document.getElementById("password");
        if (passwordInput.type === "password") {
            passwordInput.type = "text";
            document.querySelector(".input-group-text i").classList.remove("fa-eye-slash");
            document.querySelector(".input-group-text i").classList.add("fa-eye");
        } else {
            passwordInput.type = "password";
            document.querySelector(".input-group-text i").classList.remove("fa-eye");
            document.querySelector(".input-group-text i").classList.add("fa-eye-slash");
        }
    }
</script>

<style>
    /* Custom CSS for the fixed-width button */
    .btn-fixed-width {
        width: 320px;
    }
</style>
{% endblock %}

web_app/website/templates/results.html
{% extends "base.html" %}
{% block title %}Results{% endblock %}
{% block content %}
<style>

    h1 {
        margin-top: 20px;
        margin-bottom: 20px;
        color: black; /* White writing */
    }
    h5 {
        margin-top: 20px;
        margin-bottom: 20px;
        color: black; /* White writing */
    }

    /* Style the image container */
    #imageContainer {
        margin-top: 20px;
        width: 100%;
        height: 100%;
        object-fit: contain; /* or 'cover' if you want the image to cover the container */
        display: flex;
        justify-content: center;
        position: relative;
        cursor: zoom-in;
    }

    /* Style the upload button */
    #imageUpload {
        display: none; /* Hide the default upload button */
        padding: 10px 20px;
        font-size: 16px;
        color: white;
        background-color: #007bff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    #uploadLabel {
        margin-top: 10px;
        padding: 10px 20px;
        background-color: black;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s, border-color 0.3s; /* Adding a smooth transition effect */
        border: 1px solid black;
    }

    /* New CSS rule for button hover state */
    #uploadLabel:hover {
        background-color: white; /* Change the color to dark gray on hover */
        color: black;
        border-color: #888;
    }

    /* Overlay container to gray out the rest of the page */
    #overlay {
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.8);
        z-index: 9999; /* Make sure it appears above other content */
        justify-content: center;
        align-items: center;
    }

    /* Style the zoomed image */
    #zoomedImage {
        max-width: 95%;
        max-height: 95%;
    }

    .uploadButton {
        margin-top: 25px;
        padding: 10px 20px;
        font-size: 16px;
        color: white;
        background-color: #007bff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .uploadButton:hover {
        background-color: #0056b3;
        border-color: #888;
    }

    .convertButton {
        margin-top: 25px;
        padding: 10px 20px;
        font-size: 16px;
        color: white;
        background-color: #007bff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .convertButton:hover {
        background-color: #0056b3;
        border-color: #888;
        color: white;
    }

    /* Style for the image container */
    .image-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        gap: 10px; /* Adjust the gap between images */
    }

    /* Style for individual image frames */
    .image-frame {
        max-width: 210px;
        border: 2px solid #ddd; /* Border style */
        border-radius: 10px; /* Rounded edges */
        overflow: hidden;
    }

    /* Style for the image itself */
    .image {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }

</style>
<br>
<br>
<br>
<h2 align="center">Here's a process overview if you're interested ...</h2>
<br>
<div class="image-container">
    <!-- Top Row Images -->
    <div class="image-frame">
        <img class="image" src="../static/images/og_image.png" alt="Image 1">
    </div>
    <div class="image-frame">
        <img class="image" src="../static/images/pp_image.png" alt="Image 2">
    </div>
    <div class="image-frame">
        <img class="image" src="../static/images/predictions.png" alt="Image 3">
    </div>
    <!-- Bottom Row Images -->
    <div class="image-frame">
        <img class="image" src="../static/images/component_rem_img.png" alt="Image 4">
    </div>
    <div class="image-frame">
        <img class="image" src="../static/images/detected_connections_image.png" alt="Image 5">
    </div>
</div>
<br>
<br>
<div align="center">
    <!-- Replace 'your_download_endpoint' with the actual URL where you serve the file -->
    <a href="{{ url_for('views.download_file') }}" class="convertButton" id="downloadSpiceFile" download>
        Download Netlist
    </a>
</div>
{% endblock %}

web_app/website/templates/valuation.html
{% extends "base.html" %}
{% block title %}Valuation{% endblock %}
{% block content %}
<style>

    h1 {
        margin-top: 20px;
        margin-bottom: 20px;
        color: black; /* White writing */
    }
    h5 {
        margin-top: 20px;
        margin-bottom: 20px;
        color: black; /* White writing */
    }

    /* Style the image container */
    #imageContainer {
        margin-top: 20px;
        width: 100%;
        height: 100%;
        object-fit: contain; /* or 'cover' if you want the image to cover the container */
        display: flex;
        justify-content: center;
        position: relative;
        cursor: zoom-in;
    }

    /* Style the upload button */
    #processValues {
        display: none; /* Hide the default upload button */
        padding: 10px 20px;
        font-size: 16px;
        color: white;
        background-color: #007bff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    #uploadLabel {
        margin-top: 10px;
        padding: 10px 20px;
        background-color: black;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s, border-color 0.3s; /* Adding a smooth transition effect */
        border: 1px solid black;
    }

    /* New CSS rule for button hover state */
    #uploadLabel:hover {
        background-color: white; /* Change the color to dark gray on hover */
        color: black;
        border-color: #888;
    }

    /* Overlay container to gray out the rest of the page */
    #overlay {
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.8);
        z-index: 9999; /* Make sure it appears above other content */
        justify-content: center;
        align-items: center;
    }

    /* Style the zoomed image */
    #zoomedImage {
        max-width: 95%;
        max-height: 95%;
    }

    .uploadButton {
        margin-top: 25px;
        padding: 10px 20px;
        font-size: 16px;
        color: white;
        background-color: #007bff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .uploadButton:hover {
        background-color: #0056b3;
        border-color: #888;
    }

    /* Style the cross button container */
    .crossContainer {
        position: relative;
        top: 0px;
        right: 30px;
        width: 30px;
        height: 30px;
        background-color: white;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 5px;
        border: 2px solid black;
        cursor: pointer;
    }

    /* Style the cross button */
    .crossButton {
        font-size: 16px;
        color: white;
        border: none;
        background: none;
    }

    .convertButton {
        margin-top: 25px;
        padding: 10px 20px;
        font-size: 16px;
        color: white;
        background-color: #007bff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .convertButton:hover {
        background-color: #0056b3;
        border-color: #888;
    }

    .frame-container {
        border: 1px solid #ccc;
        margin-top: 0px;
        margin-right: 20px;
        border-radius: 10px;
        padding: 10px;
        width: 50%; /* Set the width to 50% for each frame container */
    }
    
    .input-row {
        display: flex;
        align-items: center; /* Vertically center-align label and input/select */
        margin-bottom: 10px;
    }
    /* Style for the input labels */
    .valueEntries {
        display: block;
        margin-bottom: 10px;
        font-weight: bold; /* Make the labels bold */
    }

    /* Style for the input fields */
    .inputValues {
        display: block;
        width: 100%; /* Make the input fields expand to full width */
        padding: 5px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .dropdownValues {
        display: block;
        width: 100%; /* Make the input fields expand to full width */
        padding: 5px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    /* CSS for the entries container with scrollbar */
    .entries-container {
        max-height: 400px; /* Adjust the maximum height as needed */
        width: auto;
        overflow-y: auto; /* Add a vertical scrollbar when content overflows */
    }

    /* Add a media query to stack the frames on small screens */
    @media screen and (max-width: 768px) {
        .frame-container {
            width: 100%; /* Set the width to 100% for each frame container on small screens */
            margin-right: 0; /* Remove right margin to make them full width */
            max-height: none; /* Remove max height on small screens */
        }

        .entries-container {
            max-height: none; /* Remove max height for entries container on small screens */
            max-width: none; /* Remove max width for entries container on small screens */
        }

        .input-row {
            flex-direction: column; /* Stack input rows vertically on small screens */
        }
    }

</style>

<!-- Add this HTML for the error message container -->
<div id="errorMessageContainer" class="alert alert-danger" style="display: none;">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <strong>Error:</strong> Please fill in all fields with valid float values.
</div>


<h1 align="center">We got the components!</h1>
<h5 align="center">So ... we just need you to specify the values.</h5>
<!-- Create a container for the entire content, centered horizontally -->
<div style="display: flex; justify-content: center; align-items: center; height: 60vh;">
    <!-- Create a frame container for the image on the left -->
    <div class="frame-container">
        <div align="center">
            <img src="../static/images/displayed_predictions.png" alt="Uploaded Drawing" style="max-height: 400px; width: auto;">
        </div>
    </div>

    <!-- Create a frame container for the entries on the right -->
    <div class="frame-container" style="max-height: 420px; max-width: 400px;">
        <div class="entries-container">
            <form method="POST" action="{{ url_for('views.results') }}">
                {% for index, label, symbol in indexed_labels %}
                    <div class="input-row">
                        {% if symbol == 'None' %}
                            <label class="valueEntries" style="width: 200px;" for="label_{{ index }}">Enter model for {{ label }}:</label>
                            <select class="dropdownValues" id="label_{{ index }}" name="label_{{ index }}" style="width: 150px;">
                                <option value="option1">1N4148</option>
                            </select>
                        {% else %}
                            <label class="valueEntries" style="width: 200px;" for="label_{{ index }}">Enter value for {{ label }} ({{ symbol }}):</label>
                            <input class="inputValues" type="number" id="label_{{ index }}" name="label_{{ index }}" min = "0" step="any" style="width: 150px;" required>
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="button-container" align="center">
                    <button type="submit" class="convertButton" id="generateSpiceFile">
                        Generate Netlist
                    </button>
                </div>
            </form>     
        </div>
    </div>
</div>
{% endblock %}